"""empty message

Revision ID: 0d4a871e5674
Revises: 00727a692652
Create Date: 2026-06-15 12:45:33.361088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4a871e5674'
down_revision: Union[str, Sequence[str], None] = '00727a692652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'expiration_date')
    op.drop_column('players', 'is_published')
    # ### end Alembic commands ###
