"""empty message

Revision ID: 1eff1e8043e4
Revises: 401da1950e2c
Create Date: 2026-06-23 17:47:12.884759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eff1e8043e4'
down_revision: Union[str, Sequence[str], None] = '401da1950e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clans', sa.Column('clan_tag', sa.String(), nullable=False))
    op.alter_column(
        'clans',
        'sieges_league',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using='sieges_league::integer',
        nullable=True,
    )
    op.alter_column(
        'clans',
        'requirements_hydra',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using='requirements_hydra::integer',
        nullable=True,
    )
    op.alter_column(
        'clans',
        'requirements_himera',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using='requirements_himera::integer',
        nullable=True,
    )
    op.alter_column(
        'clans',
        'requirements_lkv',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using='requirements_lkv::integer',
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clans', 'requirements_lkv',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clans', 'requirements_himera',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clans', 'requirements_hydra',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clans', 'sieges_league',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('clans', 'clan_tag')
    # ### end Alembic commands ###
