"""empty message

Revision ID: 27d61b41ab48
Revises: f91b2ca89061
Create Date: 2026-06-16 19:23:36.092779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d61b41ab48'
down_revision: Union[str, Sequence[str], None] = 'f91b2ca89061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clans', schema=None) as batch_op:
        batch_op.alter_column(
            'level',
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clans', schema=None) as batch_op:
        batch_op.alter_column(
            'level',
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
