"""empty message

Revision ID: 897d9a871ce2
Revises: 404c3caaebcb
Create Date: 2026-06-22 10:47:58.306967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897d9a871ce2'
down_revision: Union[str, Sequence[str], None] = '404c3caaebcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reviewer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'reviewer')
    # ### end Alembic commands ###
