"""empty message

Revision ID: b23814e9f585
Revises: 9aaee1bf7653
Create Date: 2026-06-23 16:16:22.383841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23814e9f585'
down_revision: Union[str, Sequence[str], None] = '9aaee1bf7653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'players',
        'sieges_league',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using='sieges_league::integer',
        nullable=True,
    )
    op.alter_column(
        'players',
        'requirements_hydra',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using='requirements_hydra::integer',
        nullable=True,
    )
    op.alter_column(
        'players',
        'requirements_himera',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using='requirements_himera::integer',
        nullable=True,
    )
    op.alter_column(
        'players',
        'requirements_lkv',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using='requirements_lkv::integer',
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'requirements_lkv',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('players', 'requirements_himera',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('players', 'requirements_hydra',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('players', 'sieges_league',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
