"""empty message

Revision ID: f91b2ca89061
Revises: 0d4a871e5674
Create Date: 2026-06-16 17:30:02.523559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91b2ca89061'
down_revision: Union[str, Sequence[str], None] = '0d4a871e5674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tg_tag', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('sieges_league', sa.String(), nullable=False),
    sa.Column('requirements_hydra', sa.String(), nullable=False),
    sa.Column('requirements_himera', sa.String(), nullable=False),
    sa.Column('requirements_lkv', sa.String(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clans')
    # ### end Alembic commands ###
